# Generated by Django 3.1.3 on 2020-11-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Med',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medicine_batch_no', models.IntegerField()),
                ('Medicine_name', models.CharField(max_length=50, null=True)),
                ('Medicine_Company', models.CharField(max_length=50, null=True)),
                ('Medical_quantity', models.IntegerField()),
                ('med_purchase_date', models.DateField()),
                ('Med_type', models.CharField(max_length=50, null=True)),
                ('Med_price', models.IntegerField()),
            ],
        ),
    ]
